  # Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'web'
  displayName: 'Install web dependencies'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'server'
  displayName: 'Install server dependencies'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'web'
    customCommand: 'test'
  displayName: 'Run web tests'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'server'
    customCommand: 'test'
  displayName: 'Run server tests'
