version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "web/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd web && yarn install

      - save_cache:
          paths:
            - web/node_modules
          key: v1-dependencies-{{ checksum "web/package.json" }}

      # run tests!
      - run: cd web/ && yarn test

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "server/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd server && yarn install

      - save_cache:
          paths:
            - server/node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}

      # run tests!
      - run: cd server/ && yarn test
